### ISSUE TITLE
Plunker or js fiddle?

### ISSUE THREAD

**Issue by dicbrus** [sphilee/jsPDF-CustomFonts-support#12]
Can smbd provide working plunkr or jsfiddle example?

Thank you

**Comment by aleksandrmelnyk** [comment]
yep, would be good. Cannot get ot working too.

**Comment by pacol85** [comment]
It's quite simple, the only problem I have is with aligning text, it gives me an error due to not finding widths on it.

This is my code that I'm working to print ID Cards, on this example I'm using a special font saved on my font folder.

If the error you get is with length then just try changing the encoding of the font.

`<script type="text/javascript">

    function demoFromHTML() {
        var pdf = new jsPDF({
            orientation: 'portrait',
            unit: 'in',
            format: [3.37, 2.125]
          });
        pdf.addFont("font/AIGFutura-Medium.ttf", "Futura", "normal", "UTF-8");
        pdf.setFont("Futura");
        pdf.text('NOMBRE', 0.5,1);
        pdf.setFontSize(10);
        pdf.text('APELLIDO', 0.5,1.5);
        pdf.save('Test.pdf');
    }    
</script>`

**Comment by sphilee** [comment]
Here is an easy way.

Just download this repository and run test.html.
