### ISSUE TITLE
Make CustomFonts into a plugin

### ISSUE THREAD

**Issue by rafiek** [sphilee/jsPDF-CustomFonts-support#33]
Hi,

Thank you very much for your solution. I can see that you clearly understand how to work with jspdf.
I have a request for your solution.

At the moment it seems like this is a fork of a version of jspdf. The customfonts solution is integrated into the fork. I used to have a separate jspdf dependency in my project along with some plugins. Now I need to switch the jspdf dependency with the customfonts dependency (because jspdf library is in customfonts).

It would be really nice to use customfonts as a plugin instead of a replacement for the entire jspdf library. Because I then have the freedom to down- or upgrade jspdf library.

I don't mind if you want me to help make customfonts into a plugin. Just give me few pointers on how to go about it.

regards,
Rafiek

**Comment by ytheekshana** [comment]
Yap... I need this too....

**Comment by pelaxa** [comment]
This is already a plugin, is it not?  you can use your own jsPDF, and the customfonts.js and vfs.js from the plugins folder.  you just have to be careful since jspdf had to be update to make sure it can handle new fonts, so I would do a compare between your jspdf and the version found here and incorporate that.
