### ISSUE TITLE
look like japanese language doesn't work 

### ISSUE THREAD

**Issue by rainstormza** [sphilee/jsPDF-CustomFonts-support#6]
look like japanese language doesn't work 
I try it only work with english and korean language

**Comment by sphilee** [comment]
What kind of font did you use?

**Comment by rainstormza** [comment]
example : よくあるご質問

if charactor is hiragana , it works
but if hiraga + kanji like example , it doesn't work


I use your default font 'MsGothic'

**Comment by sphilee** [comment]
`doc.setFont('MsGothic');
 doc.drawText(10, 20, 'よくあるご質問');`

It works

Kanji's Unicode is in the same position as Japanese and Chinese. Since kanji is a language created in China, I set the default fonts in Chinese. If you use doc.setFont ('Japanese') instead of the doc.setDefaultFonts(), you can use kanji in Japanese.
